CREATE TABLE `property_preferences` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `subject_type` VARCHAR(20) NOT NULL,
  `subject_uuid` CHAR(36) NOT NULL,
  `version` INT NOT NULL DEFAULT 1,
  `status` ENUM('ACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
  `transaction_types` JSON NOT NULL,
  `property_type_uuids` JSON NOT NULL,
  `property_category_uuids` JSON NOT NULL,
  `hard_criteria` JSON NOT NULL,
  `country_uuid` CHAR(36) NULL,
  `province_uuid` CHAR(36) NULL,
  `city_uuid` CHAR(36) NULL,
  `district_uuid` CHAR(36) NULL,
  `subdistrict_uuid` CHAR(36) NULL,
  `radius_km` DECIMAL(8,2) NULL,
  `latitude` DECIMAL(10,7) NULL,
  `longitude` DECIMAL(10,7) NULL,
  `budget_min` DECIMAL(24,2) NULL,
  `budget_max` DECIMAL(24,2) NULL,
  `budget_currency` CHAR(3) NULL,
  `budget_frequency` ENUM('TOTAL','PER_MONTH','PER_YEAR','PER_DAY') NULL,
  `tolerance_percent` DECIMAL(6,2) NULL,
  `bedrooms_min` INT NULL,
  `bedrooms_max` INT NULL,
  `bathrooms_min` DECIMAL(8,2) NULL,
  `bathrooms_max` DECIMAL(8,2) NULL,
  `area_sqm_min` DECIMAL(18,2) NULL,
  `area_sqm_max` DECIMAL(18,2) NULL,
  `parking_spaces_min` INT NULL,
  `parking_spaces_max` INT NULL,
  `furnished_status` VARCHAR(30) NULL,
  `condition` VARCHAR(30) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `archived_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `property_preferences_uuid_key` (`uuid`),
  UNIQUE KEY `property_preferences_subject_key` (`subject_type`,`subject_uuid`),
  KEY `property_preferences_subject_status_idx` (`subject_type`,`subject_uuid`,`status`),
  KEY `property_preferences_updated_idx` (`updated_at`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `match_scores` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `subject_type` VARCHAR(20) NOT NULL,
  `subject_uuid` CHAR(36) NOT NULL,
  `property_uuid` CHAR(36) NOT NULL,
  `listing_uuid` CHAR(36) NOT NULL,
  `score` DECIMAL(6,2) NOT NULL,
  `algorithm_version` INT NOT NULL,
  `calculated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `match_scores_uuid_key` (`uuid`),
  UNIQUE KEY `match_scores_current_key` (`subject_type`,`subject_uuid`,`listing_uuid`,`algorithm_version`),
  KEY `match_scores_subject_rank_idx` (`subject_type`,`subject_uuid`,`score`,`calculated_at`),
  KEY `match_scores_listing_version_idx` (`listing_uuid`,`algorithm_version`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `recommendations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `subject_type` VARCHAR(20) NOT NULL,
  `subject_uuid` CHAR(36) NOT NULL,
  `preference_version` INT NOT NULL,
  `algorithm_version` INT NOT NULL,
  `source` ENUM('GENERATED','REFRESHED','RECALCULATED') NOT NULL DEFAULT 'GENERATED',
  `generated_at` DATETIME(3) NOT NULL,
  `candidate_count` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `recommendations_uuid_key` (`uuid`),
  KEY `recommendations_subject_generated_idx` (`subject_type`,`subject_uuid`,`generated_at`),
  KEY `recommendations_subject_versions_idx` (`subject_type`,`subject_uuid`,`preference_version`,`algorithm_version`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `recommendation_items` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `recommendation_id` BIGINT UNSIGNED NOT NULL,
  `property_uuid` CHAR(36) NOT NULL,
  `listing_uuid` CHAR(36) NOT NULL,
  `rank` INT NOT NULL,
  `score` DECIMAL(6,2) NOT NULL,
  `explanation` JSON NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `recommendation_items_uuid_key` (`uuid`),
  UNIQUE KEY `recommendation_items_listing_key` (`recommendation_id`,`listing_uuid`),
  KEY `recommendation_items_rank_idx` (`recommendation_id`,`rank`),
  KEY `recommendation_items_listing_idx` (`listing_uuid`),
  CONSTRAINT `recommendation_items_recommendation_fk` FOREIGN KEY (`recommendation_id`) REFERENCES `recommendations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `recommendation_history` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `recommendation_id` BIGINT UNSIGNED NOT NULL,
  `subject_type` VARCHAR(20) NOT NULL,
  `subject_uuid` CHAR(36) NOT NULL,
  `source` ENUM('GENERATED','REFRESHED','RECALCULATED') NOT NULL,
  `preference_version` INT NOT NULL,
  `algorithm_version` INT NOT NULL,
  `candidate_count` INT NOT NULL,
  `generated_at` DATETIME(3) NOT NULL,
  `actor_uuid` CHAR(36) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `recommendation_history_uuid_key` (`uuid`),
  KEY `recommendation_history_subject_generated_idx` (`subject_type`,`subject_uuid`,`generated_at`),
  CONSTRAINT `recommendation_history_recommendation_fk` FOREIGN KEY (`recommendation_id`) REFERENCES `recommendations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `match_feedback` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `recommendation_item_id` BIGINT UNSIGNED NOT NULL,
  `subject_type` VARCHAR(20) NOT NULL,
  `subject_uuid` CHAR(36) NOT NULL,
  `property_uuid` CHAR(36) NOT NULL,
  `listing_uuid` CHAR(36) NOT NULL,
  `feedback` ENUM('INTERESTED','NOT_RELEVANT','HIDDEN','CONTACTED') NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `match_feedback_uuid_key` (`uuid`),
  UNIQUE KEY `match_feedback_item_subject_key` (`recommendation_item_id`,`subject_type`,`subject_uuid`),
  KEY `match_feedback_subject_idx` (`subject_type`,`subject_uuid`,`feedback`,`updated_at`),
  KEY `match_feedback_listing_idx` (`listing_uuid`,`feedback`,`updated_at`),
  CONSTRAINT `match_feedback_item_fk` FOREIGN KEY (`recommendation_item_id`) REFERENCES `recommendation_items` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;