-- Historical compatibility migration.
--
-- This migration previously depended on objects introduced by later
-- migrations (20260825170000_two_factor_authentication and
-- 20260825173000_audit_logging_hardening), which made a clean shadow
-- database impossible to build. The valid schema changes are now defined
-- in the migrations that create those objects.
--
-- Keep this migration as a no-op so the migration history remains stable.
