CREATE TABLE `property_utilities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `property_id` BIGINT UNSIGNED NOT NULL,
  `electricity_provider` VARCHAR(120) NULL,
  `electricity_capacity_kva` DECIMAL(10,2) NULL,
  `electricity_meter_number_masked` VARCHAR(32) NULL,
  `water_source` ENUM('PDAM','WELL','SPRING','RAINWATER','TANKER','OTHER','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  `water_backup_source` ENUM('PDAM','WELL','SPRING','RAINWATER','TANKER','OTHER','UNKNOWN') NULL,
  `gas_type` ENUM('LPG','NATURAL_GAS','PIPED_GAS','NONE','OTHER') NOT NULL DEFAULT 'NONE',
  `internet_fiber` BOOLEAN NOT NULL DEFAULT FALSE,
  `internet_providers` JSON NULL,
  `sewage_type` ENUM('SEPTIC_TANK','SEWER','BIOLOGICAL_TREATMENT','NONE','OTHER') NOT NULL DEFAULT 'NONE',
  `drainage_type` ENUM('OPEN_DRAIN','CLOSED_DRAIN','SOAKAWAY','STORMWATER','NONE','OTHER') NOT NULL DEFAULT 'NONE',
  `drainage_condition` ENUM('EXCELLENT','GOOD','FAIR','POOR','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  `backup_power_type` ENUM('GENERATOR','BATTERY','UPS','SOLAR_BATTERY','NONE','OTHER') NOT NULL DEFAULT 'NONE',
  `backup_power_capacity_kva` DECIMAL(10,2) NULL,
  `created_by` CHAR(36) NULL,
  `updated_by` CHAR(36) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`), UNIQUE KEY `property_utilities_uuid_key` (`uuid`), UNIQUE KEY `property_utilities_property_id_key` (`property_id`),
  KEY `property_utilities_water_idx` (`water_source`,`water_backup_source`),
  CONSTRAINT `property_utilities_property_fk` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `property_utilities_electricity_capacity_check` CHECK (`electricity_capacity_kva` IS NULL OR `electricity_capacity_kva` >= 0),
  CONSTRAINT `property_utilities_backup_capacity_check` CHECK (`backup_power_capacity_kva` IS NULL OR `backup_power_capacity_kva` >= 0)
) ENGINE=InnoDB;
