import type { PrismaClient } from '../generated/prisma/client.ts';

const REQUIRED_SEED_COUNTS = {
  authenticationUser: 1,
  authenticationUserCredential: 1,
  authenticationUserSecurity: 1,
  authorizationPermission: 1,
  authorizationRole: 1,
  authorizationRolePermission: 1,
  agentProfile: 1,
  agentSpecialization: 1,
  agentCoverage: 1,
  agentAvailability: 1,
  agentWeeklySchedule: 1,
  agentTarget: 1,
  propertyType: 1,
  propertyCategory: 1,
  propertySubcategory: 1,
  country: 1,
  province: 1,
  city: 1,
  district: 1,
  subdistrict: 1,
  facility: 1,
  propertyAmenity: 1,
  property: 1,
  propertySpecification: 1,
  propertyLocation: 1,
  propertyBuilding: 1,
  propertyFinancial: 1,
  propertyFeatures: 1,
  propertySecurity: 1,
  propertyEnvironment: 1,
  propertyUtility: 1,
  propertyLegal: 1,
  propertyOwner: 1,
  propertyRoom: 1,
  propertyCertificate: 1,
  propertyDocument: 1,
  propertyDocumentVersion: 1,
  propertyMedia: 1,
  propertyListing: 1,
  propertyListingPrice: 1,
  propertyListingPaymentOption: 1,
  propertyListingAnalytics: 1,
  propertyFacility: 1,
  propertyAmenityAssignment: 1,
  propertyAgentAssignment: 1,
  propertyHistory: 1,
  crmLeadStatus: 1,
  crmLeadStatusTransition: 1,
  crmLeadSource: 1,
  crmLeadCampaign: 1,
  crmLeadType: 1,
  crmLeadTag: 1,
  crmLeadScoreRule: 1,
  crmContact: 1,
  crmContactEmail: 1,
  crmContactPhone: 1,
  crmContactPreference: 1,
  crmLead: 1,
  crmLeadTagLink: 1,
  crmLeadHistory: 1,
  crmLeadScore: 1,
  salesPipeline: 1,
  salesPipelineStage: 1,
  salesLostReason: 1,
  salesCommissionRule: 1,
  salesOpportunity: 1,
  salesOpportunityStageHistory: 1,
  salesActivity: 1,
  salesViewing: 1,
  salesNegotiation: 1,
  salesNegotiationHistory: 1,
  salesOffer: 1,
  systemSetting: 1,
  systemFeatureFlag: 1,
  systemImportProfile: 1,
  systemIntegration: 1,
  systemIntegrationRuntime: 1,
  systemIntegrationEvent: 1,
  systemIntegrationIdempotency: 1,
  systemIntegrationOperation: 1,
  systemOperationalAlertRule: 1,
  systemActivity: 1,
} as const;

export async function verifySeedState(prisma: PrismaClient): Promise<void> {
  const entries = Object.entries(REQUIRED_SEED_COUNTS) as [keyof typeof REQUIRED_SEED_COUNTS, number][];
  const counts = await Promise.all(
    entries.map(async ([model, minimum]) => [model, await prisma[model].count(), minimum] as const),
  );

  const missing = counts.filter(([, actual, minimum]) => actual < minimum);
  if (missing.length > 0) {
    const details = missing.map(([model, actual, minimum]) => `${model}: expected >= ${minimum}, got ${actual}`).join('; ');
    throw new Error(`Seed verification failed: ${details}`);
  }
}

export const SEEDED_BASELINE_TABLES = Object.keys(REQUIRED_SEED_COUNTS);
