import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import type { SecurityAuditRepository } from '../../../common/audit/security-audit.port.js';
import { SECURITY_AUDIT_REPOSITORY } from '../../../common/audit/security-audit.port.js';
import { PropertyExtrasConflictError, PropertyExtrasInvalidStateError, PropertyExtrasNotFoundError, validateCertificateInput, validateFinancialInvariants, validateLegalInvariants, validateMedia, validateSeoInvariants, validateUtilityInvariants } from '../domain/property-extras.js';
import { PROPERTY_EXTRAS_REPOSITORY, type PropertyExtrasActor, type PropertyExtrasRepository } from '../domain/repositories/property-extras.repository.js';

@Injectable()
export class PropertyExtrasService {
  constructor(@Inject(PROPERTY_EXTRAS_REPOSITORY) private readonly repository: PropertyExtrasRepository, @Inject(SECURITY_AUDIT_REPOSITORY) private readonly audit: SecurityAuditRepository) {}
  getUtilities(propertyUuid:string){return this.run(()=>this.repository.getUtilities(propertyUuid));}
  async updateUtilities(propertyUuid:string,patch:Parameters<PropertyExtrasRepository['upsertUtilities']>[1],actor:PropertyExtrasActor){validateUtilityInvariants(patch);const result=await this.run(()=>this.repository.upsertUtilities(propertyUuid,patch,actor));await this.record('property.utilities.update','property_utilities',propertyUuid,actor,patch);return result;}
  getLegal(propertyUuid:string){return this.run(()=>this.repository.getLegal(propertyUuid));}
  async updateLegal(propertyUuid:string,patch:Parameters<PropertyExtrasRepository['upsertLegal']>[1],actor:PropertyExtrasActor){validateLegalInvariants(patch);const result=await this.run(()=>this.repository.upsertLegal(propertyUuid,patch,actor));await this.record('property.legal.update','property_legal',propertyUuid,actor,this.redactLegalPatch(patch));return result;}
  listCertificates(propertyUuid:string){return this.run(()=>this.repository.listCertificates(propertyUuid));}
  async createCertificate(propertyUuid:string,input:Parameters<PropertyExtrasRepository['createCertificate']>[1],actor:PropertyExtrasActor){validateCertificateInput(input);const result=await this.run(()=>this.repository.createCertificate(propertyUuid,input,actor));await this.record('property.certificate.create','property_certificate',propertyUuid,actor,{type:input.type,status:input.status});return result;}
  async updateCertificate(propertyUuid:string,certificateUuid:string,input:Parameters<PropertyExtrasRepository['updateCertificate']>[2],actor:PropertyExtrasActor){validateCertificateInput(input);const result=await this.run(()=>this.repository.updateCertificate(propertyUuid,certificateUuid,input,actor));await this.record('property.certificate.update','property_certificate',certificateUuid,actor,{type:input.type,status:input.status,numberChanged:input.number!==undefined});return result;}
  async deleteCertificate(propertyUuid:string,certificateUuid:string,actor:PropertyExtrasActor){await this.run(()=>this.repository.deleteCertificate(propertyUuid,certificateUuid,actor));await this.record('property.certificate.delete','property_certificate',certificateUuid,actor);}
  getFinancial(propertyUuid:string){return this.run(()=>this.repository.getFinancial(propertyUuid));}
  async updateFinancial(propertyUuid:string,patch:Parameters<PropertyExtrasRepository['upsertFinancial']>[1],actor:PropertyExtrasActor){validateFinancialInvariants(patch);const result=await this.run(()=>this.repository.upsertFinancial(propertyUuid,patch,actor));await this.record('property.financial.update','property_financial',propertyUuid,actor,patch);return result;}
  getFeatures(propertyUuid:string){return this.run(()=>this.repository.getFeatures(propertyUuid));}
  async updateFeatures(propertyUuid:string,patch:Parameters<PropertyExtrasRepository['upsertFeatures']>[1],actor:PropertyExtrasActor){const result=await this.run(()=>this.repository.upsertFeatures(propertyUuid,patch,actor));await this.record('property.features.update','property_features',propertyUuid,actor,patch);return result;}
  getSecurity(propertyUuid:string){return this.run(()=>this.repository.getSecurity(propertyUuid));}
  async updateSecurity(propertyUuid:string,patch:Parameters<PropertyExtrasRepository['upsertSecurity']>[1],actor:PropertyExtrasActor){const result=await this.run(()=>this.repository.upsertSecurity(propertyUuid,patch,actor));await this.record('property.security.update','property_security',propertyUuid,actor,patch);return result;}
  getEnvironment(propertyUuid:string){return this.run(()=>this.repository.getEnvironment(propertyUuid));}
  async updateEnvironment(propertyUuid:string,patch:Parameters<PropertyExtrasRepository['upsertEnvironment']>[1],actor:PropertyExtrasActor){const result=await this.run(()=>this.repository.upsertEnvironment(propertyUuid,patch,actor));await this.record('property.environment.update','property_environment',propertyUuid,actor,patch);return result;}
  getSeo(propertyUuid:string){return this.run(()=>this.repository.getSeo(propertyUuid));}
  async updateSeo(propertyUuid:string,patch:Parameters<PropertyExtrasRepository['upsertSeo']>[1],actor:PropertyExtrasActor){const slug=await this.run(()=>this.repository.getPropertySlug(propertyUuid));validateSeoInvariants(slug,patch);const result=await this.run(()=>this.repository.upsertSeo(propertyUuid,patch,actor));await this.record('property.seo.update','property_seo',propertyUuid,actor,patch);return result;}
  listMedia(propertyUuid:string){return this.run(()=>this.repository.listMedia(propertyUuid));}
  async addMedia(propertyUuid:string,input:Parameters<PropertyExtrasRepository['addMedia']>[1],actor:PropertyExtrasActor){validateMedia(input);const result=await this.run(()=>this.repository.addMedia(propertyUuid,input,actor));await this.record('property.media.create','property_media',propertyUuid,actor,{type:input.type,category:input.category,isCover:input.isCover});return result;}
  async updateMedia(propertyUuid:string,mediaUuid:string,input:Parameters<PropertyExtrasRepository['updateMedia']>[2],actor:PropertyExtrasActor){validateMedia(input);const result=await this.run(()=>this.repository.updateMedia(propertyUuid,mediaUuid,input,actor));await this.record('property.media.update','property_media',mediaUuid,actor,{type:input.type,category:input.category});return result;}
  async deleteMedia(propertyUuid:string,mediaUuid:string,actor:PropertyExtrasActor){await this.run(()=>this.repository.deleteMedia(propertyUuid,mediaUuid,actor));await this.record('property.media.delete','property_media',mediaUuid,actor);}
  async setCover(propertyUuid:string,mediaUuid:string,actor:PropertyExtrasActor){const result=await this.run(()=>this.repository.setCover(propertyUuid,mediaUuid,actor));await this.record('property.media.set_cover','property_media',mediaUuid,actor);return result;}
  async reorderMedia(propertyUuid:string,mediaUuids:string[],actor:PropertyExtrasActor){if(new Set(mediaUuids).size!==mediaUuids.length)throw new BadRequestException('mediaUuids must not contain duplicates');const result=await this.run(()=>this.repository.reorderMedia(propertyUuid,mediaUuids,actor));await this.record('property.media.reorder','property',propertyUuid,actor,{count:mediaUuids.length});return result;}
  private redactLegalPatch(patch:Record<string,unknown>){return {...patch,ownerReference:patch.ownerReference===undefined?undefined:patch.ownerReference===null?null:'[REDACTED]',disputes:patch.disputes===undefined?undefined:patch.disputes===null?null:'[STRUCTURED]',encumbrances:patch.encumbrances===undefined?undefined:patch.encumbrances===null?null:'[STRUCTURED]'};}
  private async record(action:string,entityType:string,entityUuid:string,actor:PropertyExtrasActor,changes?:unknown){await this.audit.record({action,actorUuid:actor.actorUuid,subjectUuid:actor.actorUuid,actorType:'user',entityType,entityUuid,ipAddress:actor.ipAddress,userAgent:actor.userAgent,requestId:actor.requestId,result:'success',changes:typeof changes==='object'&&changes!==null?(changes as Record<string,unknown>):undefined});}
  private async run<T>(operation:()=>Promise<T>):Promise<T>{try{return await operation();}catch(error:unknown){if(error instanceof PropertyExtrasNotFoundError)throw new NotFoundException(error.message);if(error instanceof PropertyExtrasConflictError)throw new ConflictException(error.message);if(error instanceof PropertyExtrasInvalidStateError)throw new BadRequestException(error.message);throw error;}}
}
