ALTER TABLE `property_categories` ADD CONSTRAINT `property_categories_type_idx2` FOREIGN KEY (`property_type_id`) REFERENCES `property_types`(`id`);

CREATE TABLE `facilities` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL, `code` VARCHAR(50) NOT NULL, `name` VARCHAR(150) NOT NULL, `slug` VARCHAR(100) NOT NULL, `category` ENUM('OUTDOOR','SECURITY','TECHNOLOGY','PARKING','CLIMATE','UTILITY','ACCESSIBILITY','RECREATION','OTHER') NOT NULL, `icon` VARCHAR(100) NULL, `description` TEXT NULL, `sort_order` INTEGER NOT NULL DEFAULT 0, `is_active` BOOLEAN NOT NULL DEFAULT true, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, `deleted_at` DATETIME(3) NULL, UNIQUE KEY `facilities_uuid_key` (`uuid`), UNIQUE KEY `facilities_code_key` (`code`), UNIQUE KEY `facilities_slug_key` (`slug`), KEY `facilities_category_idx` (`category`), KEY `facilities_active_deleted_sort_idx` (`is_active`,`deleted_at`,`sort_order`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `properties` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL, `business_code` VARCHAR(40) NOT NULL, `reference_number` VARCHAR(80) NOT NULL, `property_type_id` BIGINT UNSIGNED NOT NULL, `property_category_id` BIGINT UNSIGNED NOT NULL, `property_subcategory_id` BIGINT UNSIGNED NULL, `subdistrict_id` BIGINT UNSIGNED NULL, `title` VARCHAR(200) NOT NULL, `slug` VARCHAR(220) NOT NULL, `short_description` VARCHAR(500) NULL, `description` TEXT NULL, `status` ENUM('DRAFT','IN_REVIEW','ACTIVE','ARCHIVED','SOLD','RENTED') NOT NULL DEFAULT 'DRAFT', `availability_status` ENUM('AVAILABLE','UNAVAILABLE') NOT NULL DEFAULT 'AVAILABLE', `available_from` DATETIME(3) NULL, `available_to` DATETIME(3) NULL, `version` INTEGER NOT NULL DEFAULT 1, `published_at` DATETIME(3) NULL, `verified_at` DATETIME(3) NULL, `created_by` CHAR(36) NULL, `updated_by` CHAR(36) NULL, `verified_by` CHAR(36) NULL, `deleted_at` DATETIME(3) NULL, `deleted_by` CHAR(36) NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL, UNIQUE KEY `properties_uuid_key` (`uuid`), UNIQUE KEY `properties_business_code_key` (`business_code`), UNIQUE KEY `properties_reference_number_key` (`reference_number`), UNIQUE KEY `properties_slug_key` (`slug`), KEY `properties_status_deleted_updated_idx` (`status`,`deleted_at`,`updated_at`,`id`), KEY `properties_availability_idx` (`availability_status`,`available_from`,`available_to`), KEY `properties_type_category_subcategory_idx` (`property_type_id`,`property_category_id`,`property_subcategory_id`), KEY `properties_subdistrict_idx` (`subdistrict_id`), KEY `properties_deleted_idx` (`deleted_at`), PRIMARY KEY (`id`), CONSTRAINT `properties_type_fk` FOREIGN KEY (`property_type_id`) REFERENCES `property_types`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT, CONSTRAINT `properties_category_fk` FOREIGN KEY (`property_category_id`) REFERENCES `property_categories`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT, CONSTRAINT `properties_subcategory_fk` FOREIGN KEY (`property_subcategory_id`) REFERENCES `property_subcategories`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT, CONSTRAINT `properties_subdistrict_fk` FOREIGN KEY (`subdistrict_id`) REFERENCES `subdistricts`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `property_facilities` (`property_id` BIGINT UNSIGNED NOT NULL, `facility_id` BIGINT UNSIGNED NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`property_id`,`facility_id`), KEY `property_facilities_facility_idx` (`facility_id`), CONSTRAINT `property_facilities_property_fk` FOREIGN KEY (`property_id`) REFERENCES `properties`(`id`) ON UPDATE CASCADE ON DELETE CASCADE, CONSTRAINT `property_facilities_facility_fk` FOREIGN KEY (`facility_id`) REFERENCES `facilities`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `property_categories` DROP FOREIGN KEY `property_categories_type_idx2`;
