export type PermissionSeed = {
  name: string;
  code: string;
  module: string;
  domain: string;
  action: string;
};

export const PERMISSIONS: readonly PermissionSeed[] = [
  { name: 'View Users', code: 'users.read', module: 'users', domain: 'users', action: 'read' },
  { name: 'Create Users', code: 'users.create', module: 'users', domain: 'users', action: 'create' },
  { name: 'Update Users', code: 'users.update', module: 'users', domain: 'users', action: 'update' },
  { name: 'Delete Users', code: 'users.delete', module: 'users', domain: 'users', action: 'delete' },
  { name: 'View Roles', code: 'roles.read', module: 'roles', domain: 'roles', action: 'read' },
  { name: 'Create Roles', code: 'roles.create', module: 'roles', domain: 'roles', action: 'create' },
  { name: 'Update Roles', code: 'roles.update', module: 'roles', domain: 'roles', action: 'update' },
  { name: 'Delete Roles', code: 'roles.delete', module: 'roles', domain: 'roles', action: 'delete' },
  { name: 'Manage Roles', code: 'roles.manage', module: 'roles', domain: 'roles', action: 'manage' },
  { name: 'View Permissions', code: 'permissions.read', module: 'permissions', domain: 'permissions', action: 'read' },
  { name: 'Create Permissions', code: 'permissions.create', module: 'permissions', domain: 'permissions', action: 'create' },
  { name: 'Update Permissions', code: 'permissions.update', module: 'permissions', domain: 'permissions', action: 'update' },
  { name: 'Delete Permissions', code: 'permissions.delete', module: 'permissions', domain: 'permissions', action: 'delete' },
  { name: 'Manage Permissions', code: 'permissions.manage', module: 'permissions', domain: 'permissions', action: 'manage' },
  { name: 'Manage Protected Roles', code: 'roles.manage.protected', module: 'roles', domain: 'manage', action: 'protected' },
  { name: 'Manage Protected Permissions', code: 'permissions.manage.protected', module: 'permissions', domain: 'manage', action: 'protected' },
  { name: 'Create Properties', code: 'properties.create', module: 'property', domain: 'properties', action: 'create' },
  { name: 'Read Properties', code: 'properties.read', module: 'property', domain: 'properties', action: 'read' },
  { name: 'Update Properties', code: 'properties.update', module: 'property', domain: 'properties', action: 'update' },
  { name: 'Delete Properties', code: 'properties.delete', module: 'property', domain: 'properties', action: 'delete' },
  { name: 'Verify Properties', code: 'properties.verify', module: 'property', domain: 'properties', action: 'verify' },
  { name: 'Publish Properties', code: 'properties.publish', module: 'property', domain: 'properties', action: 'publish' },
  { name: 'Archive Properties', code: 'properties.archive', module: 'property', domain: 'properties', action: 'archive' },
  { name: 'Manage Properties', code: 'properties.manage', module: 'property', domain: 'properties', action: 'manage' },
  { name: 'Read Sensitive Property Data', code: 'properties.sensitive.read', module: 'property', domain: 'properties', action: 'sensitive.read' },
  { name: 'Read Property Specifications', code: 'property-specifications.read', module: 'property', domain: 'property-specifications', action: 'read' },
  { name: 'Update Property Specifications', code: 'property-specifications.update', module: 'property', domain: 'property-specifications', action: 'update' },
  { name: 'Read Property Locations', code: 'property-locations.read', module: 'property', domain: 'property-locations', action: 'read' },
  { name: 'Update Property Locations', code: 'property-locations.update', module: 'property', domain: 'property-locations', action: 'update' },
  { name: 'Read Property Buildings', code: 'property-buildings.read', module: 'property', domain: 'property-buildings', action: 'read' },
  { name: 'Update Property Buildings', code: 'property-buildings.update', module: 'property', domain: 'property-buildings', action: 'update' },
  { name: 'Read Property Rooms', code: 'property-rooms.read', module: 'property', domain: 'property-rooms', action: 'read' },
  { name: 'Create Property Rooms', code: 'property-rooms.create', module: 'property', domain: 'property-rooms', action: 'create' },
  { name: 'Update Property Rooms', code: 'property-rooms.update', module: 'property', domain: 'property-rooms', action: 'update' },
  { name: 'Delete Property Rooms', code: 'property-rooms.delete', module: 'property', domain: 'property-rooms', action: 'delete' },
  { name: 'Reorder Property Rooms', code: 'property-rooms.reorder', module: 'property', domain: 'property-rooms', action: 'reorder' },
  { name: 'Read Property Facilities', code: 'property-facilities.read', module: 'property', domain: 'property-facilities', action: 'read' },
  { name: 'Attach Property Facilities', code: 'property-facilities.attach', module: 'property', domain: 'property-facilities', action: 'attach' },
  { name: 'Bulk Attach Property Facilities', code: 'property-facilities.bulk-attach', module: 'property', domain: 'property-facilities', action: 'bulk-attach' },
  { name: 'Update Property Facilities', code: 'property-facilities.update', module: 'property', domain: 'property-facilities', action: 'update' },
  { name: 'Detach Property Facilities', code: 'property-facilities.detach', module: 'property', domain: 'property-facilities', action: 'detach' },
  { name: 'Read Property Utilities', code: 'property-utilities.read', module: 'property', domain: 'property-utilities', action: 'read' },
  { name: 'Update Property Utilities', code: 'property-utilities.update', module: 'property', domain: 'property-utilities', action: 'update' },
  { name: 'Read Property Legal', code: 'property-legal.read', module: 'property', domain: 'property-legal', action: 'read' },
  { name: 'Update Property Legal', code: 'property-legal.update', module: 'property', domain: 'property-legal', action: 'update' },
  { name: 'Read Property Financial', code: 'property-financial.read', module: 'property', domain: 'property-financial', action: 'read' },
  { name: 'Update Property Financial', code: 'property-financial.update', module: 'property', domain: 'property-financial', action: 'update' },
  { name: 'Read Property Media', code: 'property-media.read', module: 'property', domain: 'property-media', action: 'read' },
  { name: 'Create Property Media', code: 'property-media.create', module: 'property', domain: 'property-media', action: 'create' },
  { name: 'Update Property Media', code: 'property-media.update', module: 'property', domain: 'property-media', action: 'update' },
  { name: 'Delete Property Media', code: 'property-media.delete', module: 'property', domain: 'property-media', action: 'delete' },
  { name: 'Reorder Property Media', code: 'property-media.reorder', module: 'property', domain: 'property-media', action: 'reorder' },
  { name: 'Set Property Media Cover', code: 'property-media.set-cover', module: 'property', domain: 'property-media', action: 'set-cover' },
  { name: 'Assign Property Agent', code: 'property-agents.assign', module: 'property', domain: 'property-agents', action: 'assign' },
  { name: 'Change Property Agent', code: 'property-agents.change', module: 'property', domain: 'property-agents', action: 'change' },
  { name: 'Manage Property Owners', code: 'property-owners.manage', module: 'property', domain: 'property-owners', action: 'manage' },
  { name: 'Read Listings', code: 'listings.read', module: 'property', domain: 'listings', action: 'read' },
  { name: 'Create Listings', code: 'listings.create', module: 'property', domain: 'listings', action: 'create' },
  { name: 'Update Listings', code: 'listings.update', module: 'property', domain: 'listings', action: 'update' },
  { name: 'Manage Listings', code: 'listings.manage', module: 'property', domain: 'listings', action: 'manage' },
  { name: 'Submit Listings for Review', code: 'listings.submit-review', module: 'property', domain: 'listings', action: 'submit-review' },
  { name: 'Verify Listings', code: 'listings.verify', module: 'property', domain: 'listings', action: 'verify' },
  { name: 'Reject Listings', code: 'listings.reject', module: 'property', domain: 'listings', action: 'reject' },
  { name: 'Activate Listings', code: 'listings.activate', module: 'property', domain: 'listings', action: 'activate' },
  { name: 'Publish Listings', code: 'listings.publish', module: 'property', domain: 'listings', action: 'publish' },
  { name: 'Unpublish Listings', code: 'listings.unpublish', module: 'property', domain: 'listings', action: 'unpublish' },
  { name: 'Archive Listings', code: 'listings.archive', module: 'property', domain: 'listings', action: 'archive' },
  { name: 'Restore Listings', code: 'listings.restore', module: 'property', domain: 'listings', action: 'restore' },
  { name: 'Mark Listings Sold', code: 'listings.sold', module: 'property', domain: 'listings', action: 'sold' },
  { name: 'Mark Listings Rented', code: 'listings.rented', module: 'property', domain: 'listings', action: 'rented' },
  { name: 'Expire Listings', code: 'listings.expire', module: 'property', domain: 'listings', action: 'expire' },
  { name: 'Duplicate Listings', code: 'listings.duplicate', module: 'property', domain: 'listings', action: 'duplicate' },
  { name: 'Read Listing Analytics', code: 'listings.analytics.read', module: 'property', domain: 'listings', action: 'analytics.read' },
];
