export type PermissionSeed = {
  name: string;
  code: string;
  module: string;
  domain: string;
  action: string;
};

export const PERMISSIONS: readonly PermissionSeed[] = [
  { name: 'View Users', code: 'users.read', module: 'users', domain: 'users', action: 'read' },
  { name: 'Create Users', code: 'users.create', module: 'users', domain: 'users', action: 'create' },
  { name: 'Update Users', code: 'users.update', module: 'users', domain: 'users', action: 'update' },
  { name: 'Delete Users', code: 'users.delete', module: 'users', domain: 'users', action: 'delete' },
  { name: 'View Roles', code: 'roles.read', module: 'roles', domain: 'roles', action: 'read' },
  { name: 'Create Roles', code: 'roles.create', module: 'roles', domain: 'roles', action: 'create' },
  { name: 'Update Roles', code: 'roles.update', module: 'roles', domain: 'roles', action: 'update' },
  { name: 'Delete Roles', code: 'roles.delete', module: 'roles', domain: 'roles', action: 'delete' },
  { name: 'Manage Roles', code: 'roles.manage', module: 'roles', domain: 'roles', action: 'manage' },
  { name: 'View Permissions', code: 'permissions.read', module: 'permissions', domain: 'permissions', action: 'read' },
  { name: 'Create Permissions', code: 'permissions.create', module: 'permissions', domain: 'permissions', action: 'create' },
  { name: 'Update Permissions', code: 'permissions.update', module: 'permissions', domain: 'permissions', action: 'update' },
  { name: 'Delete Permissions', code: 'permissions.delete', module: 'permissions', domain: 'permissions', action: 'delete' },
  { name: 'Manage Permissions', code: 'permissions.manage', module: 'permissions', domain: 'permissions', action: 'manage' },
  { name: 'Manage Protected Roles', code: 'roles.manage.protected', module: 'roles', domain: 'manage', action: 'protected' },
  { name: 'Manage Protected Permissions', code: 'permissions.manage.protected', module: 'permissions', domain: 'manage', action: 'protected' },
  { name: 'Read System Settings', code: 'system.settings.read', module: 'system', domain: 'settings', action: 'read' },
  { name: 'Update System Settings', code: 'system.settings.update', module: 'system', domain: 'settings', action: 'update' },
  { name: 'Read System Activity', code: 'system.activity.read', module: 'system', domain: 'activity', action: 'read' },
  { name: 'Read System Notifications', code: 'system.notifications.read', module: 'system', domain: 'notifications', action: 'read' },
  { name: 'Read System Jobs', code: 'system.jobs.read', module: 'system', domain: 'jobs', action: 'read' },
  { name: 'Retry System Jobs', code: 'system.jobs.retry', module: 'system', domain: 'jobs', action: 'retry' },
  { name: 'Cancel System Jobs', code: 'system.jobs.cancel', module: 'system', domain: 'jobs', action: 'cancel' },

  { name: 'Create Property Types', code: 'property-types.create', module: 'property', domain: 'property-types', action: 'create' },
  { name: 'Read Property Types', code: 'property-types.read', module: 'property', domain: 'property-types', action: 'read' },
  { name: 'Update Property Types', code: 'property-types.update', module: 'property', domain: 'property-types', action: 'update' },
  { name: 'Delete Property Types', code: 'property-types.delete', module: 'property', domain: 'property-types', action: 'delete' },
  { name: 'Create Property Categories', code: 'property-categories.create', module: 'property', domain: 'property-categories', action: 'create' },
  { name: 'Read Property Categories', code: 'property-categories.read', module: 'property', domain: 'property-categories', action: 'read' },
  { name: 'Update Property Categories', code: 'property-categories.update', module: 'property', domain: 'property-categories', action: 'update' },
  { name: 'Delete Property Categories', code: 'property-categories.delete', module: 'property', domain: 'property-categories', action: 'delete' },
  { name: 'Create Property Subcategories', code: 'property-subcategories.create', module: 'property', domain: 'property-subcategories', action: 'create' },
  { name: 'Read Property Subcategories', code: 'property-subcategories.read', module: 'property', domain: 'property-subcategories', action: 'read' },
  { name: 'Update Property Subcategories', code: 'property-subcategories.update', module: 'property', domain: 'property-subcategories', action: 'update' },
  { name: 'Delete Property Subcategories', code: 'property-subcategories.delete', module: 'property', domain: 'property-subcategories', action: 'delete' },
  { name: 'Manage Locations', code: 'locations.manage', module: 'property', domain: 'locations', action: 'manage' },
  { name: 'Read Locations', code: 'locations.read', module: 'property', domain: 'locations', action: 'read' },
  { name: 'Create Facilities', code: 'facilities.create', module: 'property', domain: 'facilities', action: 'create' },
  { name: 'Read Facilities', code: 'facilities.read', module: 'property', domain: 'facilities', action: 'read' },
  { name: 'Update Facilities', code: 'facilities.update', module: 'property', domain: 'facilities', action: 'update' },
  { name: 'Delete Facilities', code: 'property', domain: 'facilities', action: 'delete' },

  { name: 'Create Properties', code: 'properties.create', module: 'property', domain: 'properties', action: 'create' },
  { name: 'Read Properties', code: 'properties.read', module: 'property', domain: 'properties', action: 'read' },
  { name: 'Update Properties', code: 'properties.update', module: 'property', domain: 'properties', action: 'update' },
  { name: 'Delete Properties', code: 'properties.delete', module: 'property', domain: 'properties', action: 'delete' },
  { name: 'Verify Properties', code: 'properties.verify', module: 'property', domain: 'properties', action: 'verify' },
  { name: 'Publish Properties', code: 'properties.publish', module: 'property', domain: 'properties', action: 'publish' },
  { name: 'Archive Properties', code: 'properties.archive', module: 'property', domain: 'properties', action: 'archive' },
  { name: 'Manage Properties', code: 'properties.manage', module: 'property', domain: 'properties', action: 'manage' },
  { name: 'Read Sensitive Property Data', code: 'properties.sensitive.read', module: 'property', domain: 'properties', action: 'sensitive.read' },

  { name: 'Read Property Specifications', code: 'property-specifications.read', module: 'property', domain: 'property-specifications', action: 'read' },
  { name: 'Create Property Specifications', code: 'property-specifications.create', module: 'property', domain: 'property-specifications', action: 'create' },
  { name: 'Update Property Specifications', code: 'property-specifications.update', module: 'property', domain: 'property-specifications', action: 'update' },
  { name: 'Delete Property Specifications', code: 'property-specifications.delete', module: 'property', domain: 'property-specifications', action: 'delete' },

  { name: 'Read Property Locations', code: 'property-locations.read', module: 'property', domain: 'property-locations', action: 'read' },
  { name: 'Create Property Locations', code: 'property-locations.create', module: 'property', domain: 'property-locations', action: 'create' },
  { name: 'Update Property Locations', code: 'property-locations.update', module: 'property', domain: 'property-locations', action: 'update' },
  { name: 'Delete Property Locations', code: 'property-locations.delete', module: 'property', domain: 'property-locations', action: 'delete' },

  { name: 'Read Property Buildings', code: 'property-buildings.read', module: 'property', domain: 'property-buildings', action: 'read' },
  { name: 'Create Property Buildings', code: 'property-buildings.create', module: 'property', domain: 'property-buildings', action: 'create' },
  { name: 'Update Property Buildings', code: 'property-buildings.update', module: 'property', domain: 'property-buildings', action: 'update' },
  { name: 'Delete Property Buildings', code: 'property-buildings.delete', module: 'property', domain: 'property-buildings', action: 'delete' },

  { name: 'Read Property Rooms', code: 'property-rooms.read', module: 'property', domain: 'property-rooms', action: 'read' },
  { name: 'Create Property Rooms', code: 'property-rooms.create', module: 'property', domain: 'property-rooms', action: 'create' },
  { name: 'Update Property Rooms', code: 'property-rooms.update', module: 'property', domain: 'property-rooms', action: 'update' },
  { name: 'Delete Property Rooms', code: 'property-rooms.delete', module: 'property', domain: 'property-rooms', action: 'delete' },
  { name: 'Reorder Property Rooms', code: 'property-rooms.reorder', module: 'property', domain: 'property-rooms', action: 'reorder' },

  { name: 'Read Property Facilities', code: 'property-facilities.read', module: 'property', domain: 'property-facilities', action: 'read' },
  { name: 'Create Property Facility Assignments', code: 'property-facilities.create', module: 'property', domain: 'property-facilities', action: 'create' },
  { name: 'Attach Property Facilities', code: 'property-facilities.attach', module: 'property', domain: 'property-facilities', action: 'attach' },
  { name: 'Bulk Attach Property Facilities', code: 'property-facilities.bulk-attach', module: 'property', domain: 'property-facilities', action: 'bulk-attach' },
  { name: 'Update Property Facilities', code: 'property-facilities.update', module: 'property', domain: 'property-facilities', action: 'update' },
  { name: 'Detach Property Facilities', code: 'property-facilities.detach', module: 'property', domain: 'property-facilities', action: 'detach' },
  { name: 'Delete Property Facility Assignments', code: 'property-facilities.delete', module: 'property', domain: 'property-facilities', action: 'delete' },

  { name: 'Read Property Utilities', code: 'property-utilities.read', module: 'property', domain: 'property-utilities', action: 'read' },
  { name: 'Create Property Utilities', code: 'property-utilities.create', module: 'property', domain: 'property-utilities', action: 'create' },
  { name: 'Update Property Utilities', code: 'property-utilities.update', module: 'property', domain: 'property-utilities', action: 'update' },
  { name: 'Delete Property Utilities', code: 'property-utilities.delete', module: 'property', domain: 'property-utilities', action: 'delete' },

  { name: 'Read Property Legal', code: 'property-legal.read', module: 'property', domain: 'property-legal', action: 'read' },
  { name: 'Create Property Legal Records', code: 'property-legal.create', module: 'property', domain: 'property-legal', action: 'create' },
  { name: 'Update Property Legal', code: 'property-legal.update', module: 'property', domain: 'property-legal', action: 'update' },
  { name: 'Delete Property Legal Records', code: 'property-legal.delete', module: 'property', domain: 'property-legal', action: 'delete' },

  { name: 'Read Property Certificates', code: 'property-certificates.read', module: 'property', domain: 'property-certificates', action: 'read' },
  { name: 'Create Property Certificates', code: 'property-certificates.create', module: 'property', domain: 'property-certificates', action: 'create' },
  { name: 'Update Property Certificates', code: 'property-certificates.update', module: 'property', domain: 'property-certificates', action: 'update' },
  { name: 'Delete Property Certificates', code: 'property-certificates.delete', module: 'property', domain: 'property-certificates', action: 'delete' },

  { name: 'Read Property Financial', code: 'property-financial.read', module: 'property', domain: 'property-financial', action: 'read' },
  { name: 'Create Property Financial Records', code: 'property-financial.create', module: 'property', domain: 'property-financial', action: 'create' },
  { name: 'Update Property Financial', code: 'property-financial.update', module: 'property', domain: 'property-financial', action: 'update' },
  { name: 'Delete Property Financial Records', code: 'property-financial.delete', module: 'property', domain: 'property-financial', action: 'delete' },

  { name: 'Create Property Features', code: 'property-features.create', module: 'property', domain: 'property-features', action: 'create' },
  { name: 'Read Property Features', code: 'property-features.read', module: 'property', domain: 'property-features', action: 'read' },
  { name: 'Update Property Features', code: 'property-features.update', module: 'property', domain: 'property-features', action: 'update' },
  { name: 'Delete Property Features', code: 'property-features.delete', module: 'property', domain: 'property-features', action: 'delete' },

  { name: 'Create Property Security Records', code: 'property-security.create', module: 'property', domain: 'property-security', action: 'create' },
  { name: 'Read Property Security Records', code: 'property-security.read', module: 'property', domain: 'property-security', action: 'read' },
  { name: 'Update Property Security Records', code: 'property-security.update', module: 'property', domain: 'property-security', action: 'update' },
  { name: 'Delete Property Security Records', code: 'property-security.delete', module: 'property', domain: 'property-security', action: 'delete' },

  { name: 'Create Property Environment Records', code: 'property-environment.create', module: 'property', domain: 'property-environment', action: 'create' },
  { name: 'Read Property Environment Records', code: 'property-environment.read', module: 'property', domain: 'property-environment', action: 'read' },
  { name: 'Update Property Environment Records', code: 'property-environment.update', module: 'property', domain: 'property-environment', action: 'update' },
  { name: 'Delete Property Environment Records', code: 'property-environment.delete', module: 'property', domain: 'property-environment', action: 'delete' },

  { name: 'Create Property SEO', code: 'property-seo.create', module: 'property', domain: 'property-seo', action: 'create' },
  { name: 'Read Property SEO', code: 'property-seo.read', module: 'property', domain: 'property-seo', action: 'read' },
  { name: 'Update Property SEO', code: 'property-seo.update', module: 'property', domain: 'property-seo', action: 'update' },
  { name: 'Delete Property SEO', code: 'property-seo.delete', module: 'property', domain: 'property-seo', action: 'delete' },

  { name: 'Read Property Media', code: 'property-media.read', module: 'property', domain: 'property-media', action: 'read' },
  { name: 'Create Property Media', code: 'property-media.create', module: 'property', domain: 'property-media', action: 'create' },
  { name: 'Update Property Media', code: 'property-media.update', module: 'property', domain: 'property-media', action: 'update' },
  { name: 'Delete Property Media', code: 'property-media.delete', module: 'property', domain: 'property-media', action: 'delete' },
  { name: 'Reorder Property Media', code: 'property-media.reorder', module: 'property', domain: 'property-media', action: 'reorder' },
  { name: 'Set Property Media Cover', code: 'property-media.set-cover', module: 'property', domain: 'property-media', action: 'set-cover' },

  { name: 'Assign Property Agent', code: 'property-agents.assign', module: 'property', domain: 'property-agents', action: 'assign' },
  { name: 'Create Property Agents', code: 'property-agents.create', module: 'property', domain: 'property-agents', action: 'create' },
  { name: 'Read Property Agents', code: 'property-agents.read', module: 'property', domain: 'property-agents', action: 'read' },
  { name: 'Update Property Agents', code: 'property-agents.update', module: 'property', domain: 'property-agents', action: 'update' },
  { name: 'Delete Property Agents', code: 'property-agents.delete', module: 'property', domain: 'property-agents', action: 'delete' },
  { name: 'Change Property Agent', code: 'property-agents.change', module: 'property', domain: 'property-agents', action: 'change' },
  { name: 'Manage Property Owners', code: 'property-owners.manage', module: 'property', domain: 'property-owners', action: 'manage' },

  { name: 'Read Listings', code: 'listings.read', module: 'property', domain: 'listings', action: 'read' },
  { name: 'Create Listings', code: 'listings.create', module: 'property', domain: 'listings', action: 'create' },
  { name: 'Update Listings', code: 'listings.update', module: 'property', domain: 'listings', action: 'update' },
  { name: 'Delete Listings', code: 'listings.delete', module: 'property', domain: 'listings', action: 'delete' },
  { name: 'Manage Listings', code: 'listings.manage', module: 'property', domain: 'listings', action: 'manage' },
  { name: 'Submit Listings for Review', code: 'listings.submit-review', module: 'property', domain: 'listings', action: 'submit-review' },
  { name: 'Verify Listings', code: 'listings.verify', module: 'property', domain: 'listings', action: 'verify' },
  { name: 'Reject Listings', code: 'listings.reject', module: 'property', domain: 'listings', action: 'reject' },
  { name: 'Activate Listings', code: 'listings.activate', module: 'property', domain: 'listings', action: 'activate' },
  { name: 'Publish Listings', code: 'listings.publish', module: 'property', domain: 'listings', action: 'publish' },
  { name: 'Unpublish Listings', code: 'listings.unpublish', module: 'property', domain: 'listings', action: 'unpublish' },
  { name: 'Archive Listings', code: 'listings.archive', module: 'property', domain: 'listings', action: 'archive' },
  { name: 'Restore Listings', code: 'listings.restore', module: 'property', domain: 'listings', action: 'restore' },
  { name: 'Mark Listings Sold', code: 'listings.sold', module: 'property', domain: 'listings', action: 'sold' },
  { name: 'Mark Listings Rented', code: 'listings.rented', module: 'property', domain: 'listings', action: 'rented' },
  { name: 'Expire Listings', code: 'listings.expire', module: 'property', domain: 'listings', action: 'expire' },
  { name: 'Duplicate Listings', code: 'listings.duplicate', module: 'property', domain: 'listings', action: 'duplicate' },
  { name: 'Read Listing Analytics', code: 'listings.analytics.read', module: 'property', domain: 'listings', action: 'analytics.read' },

  { name: 'Read Automation Workflows', code: 'automation.workflows.read', module: 'automation', domain: 'workflows', action: 'read' },
  { name: 'Create Automation Workflows', code: 'automation.workflows.create', module: 'automation', domain: 'workflows', action: 'create' },
  { name: 'Update Automation Workflows', code: 'automation.workflows.update', module: 'automation', domain: 'workflows', action: 'update' },
  { name: 'Publish Automation Workflows', code: 'automation.workflows.publish', module: 'automation', domain: 'workflows', action: 'publish' },
  { name: 'Activate Automation Workflows', code: 'automation.workflows.activate', module: 'automation', domain: 'workflows', action: 'activate' },
  { name: 'Pause Automation Workflows', code: 'automation.workflows.pause', module: 'automation', domain: 'workflows', action: 'pause' },
  { name: 'Archive Automation Workflows', code: 'automation.workflows.archive', module: 'automation', domain: 'workflows', action: 'archive' },
  { name: 'Execute Automation', code: 'automation.execute', module: 'automation', domain: 'execution', action: 'execute' },
  { name: 'Read Automation Executions', code: 'automation.executions.read', module: 'automation', domain: 'execution', action: 'read' },
  { name: 'Retry Automation Executions', code: 'automation.executions.retry', module: 'automation', domain: 'execution', action: 'retry' },
  { name: 'Cancel Automation Executions', code: 'automation.executions.cancel', module: 'automation', domain: 'execution', action: 'cancel' },
];
