export const SALES_PERMISSIONS = [
  ['Create Sales Pipelines', 'sales.pipelines.create', 'sales', 'pipelines', 'create'],
  ['Read Sales Pipelines', 'sales.pipelines.read', 'sales', 'pipelines', 'read'],
  ['Update Sales Pipelines', 'sales.pipelines.update', 'sales', 'pipelines', 'update'],
  ['Archive Sales Pipelines', 'sales.pipelines.archive', 'sales', 'pipelines', 'archive'],
  ['Create Sales Pipeline Stages', 'sales.pipelines.stages.create', 'sales', 'pipeline-stages', 'create'],
  ['Update Sales Pipeline Stages', 'sales.pipelines.stages.update', 'sales', 'pipeline-stages', 'update'],
  ['Reorder Sales Pipeline Stages', 'sales.pipelines.stages.reorder', 'sales', 'pipeline-stages', 'reorder'],
  ['Create Sales Opportunities', 'sales.opportunities.create', 'sales', 'opportunities', 'create'],
  ['Read Sales Opportunities', 'sales.opportunities.read', 'sales', 'opportunities', 'read'],
  ['Update Sales Opportunities', 'sales.opportunities.update', 'sales', 'opportunities', 'update'],
  ['Assign Sales Opportunities', 'sales.opportunities.assign', 'sales', 'opportunities', 'assign'],
  ['Transition Sales Opportunities', 'sales.opportunities.transition', 'sales', 'opportunities', 'transition'],
  ['Lose Sales Opportunities', 'sales.opportunities.lost', 'sales', 'opportunities', 'lost'],
  ['Create Sales Activities', 'sales.activities.create', 'sales', 'activities', 'create'],
  ['Read Sales Activities', 'sales.activities.read', 'sales', 'activities', 'read'],
  ['Update Sales Activities', 'sales.activities.update', 'sales', 'activities', 'update'],
  ['Create Sales Viewings', 'sales.viewings.create', 'sales', 'viewings', 'create'],
  ['Read Sales Viewings', 'sales.viewings.read', 'sales', 'viewings', 'read'],
  ['Update Sales Viewings', 'sales.viewings.update', 'sales', 'viewings', 'update'],
  ['Create Sales Negotiations', 'sales.negotiations.create', 'sales', 'negotiations', 'create'],
  ['Read Sales Negotiations', 'sales.negotiations.read', 'sales', 'negotiations', 'read'],
  ['Transition Sales Negotiations', 'sales.negotiations.transition', 'sales', 'negotiations', 'transition'],
  ['Create Sales Offers', 'sales.offers.create', 'sales', 'offers', 'create'],
  ['Read Sales Offers', 'sales.offers.read', 'sales', 'offers', 'read'],
  ['Transition Sales Offers', 'sales.offers.transition', 'sales', 'offers', 'transition'],
  ['Create Sales Deals', 'sales.deals.create', 'sales', 'deals', 'create'],
  ['Read Sales Deals', 'sales.deals.read', 'sales', 'deals', 'read'],
  ['Update Sales Deal Items', 'sales.deals.items.update', 'sales', 'deal-items', 'update'],
  ['Transition Sales Deals', 'sales.deals.transition', 'sales', 'deals', 'transition'],
  ['Lose Sales Deals', 'sales.deals.lost', 'sales', 'deals', 'lost'],
  ['Reopen Sales Deals', 'sales.deals.reopen', 'sales', 'deals', 'reopen'],
  ['Create Sales Closings', 'sales.closing.create', 'sales', 'closing', 'create'],
  ['Read Lost Reasons', 'sales.lost-reasons.read', 'sales', 'lost-reasons', 'read'],
  ['Manage Lost Reasons', 'sales.lost-reasons.manage', 'sales', 'lost-reasons', 'manage'],
  ['Manage Commission Rules', 'sales.commission.rules.manage', 'sales', 'commission-rules', 'manage'],
  ['Calculate Commission', 'sales.commission.calculate', 'sales', 'commission', 'calculate'],
  ['Read Commission', 'sales.commission.read', 'sales', 'commission', 'read'],
  ['Approve Commission', 'sales.commission.approve', 'sales', 'commission', 'approve'],
  ['Settle Commission', 'sales.commission.settle', 'sales', 'commission', 'settle'],
  ['Read Sales Forecast', 'sales.forecast.read', 'sales', 'forecast', 'read'],
].map(([name, code, module, domain, action]) => ({
  name,
  code,
  module,
  domain,
  action,
}));
