import { Type } from 'class-transformer';
import { IsBoolean, IsEmail, IsIn, IsInt, IsISO8601, IsOptional, IsString, IsUUID, Max, Min, MinLength } from 'class-validator';
export class PageDto { @Type(()=>Number) @IsOptional() @IsInt() @Min(1) page=1; @Type(()=>Number) @IsOptional() @IsInt() @Min(1) @Max(100) limit=20; @IsOptional() @IsString() search?:string; @IsOptional() @IsString() sortBy?:string; @IsOptional() @IsIn(['asc','desc']) sortDirection:'asc'|'desc'='desc'; }
export class ContactDto { @IsString() @MinLength(1) firstName!:string; @IsOptional() @IsString() lastName?:string; @IsString() @MinLength(1) displayName!:string; @IsOptional() @IsString() companyName?:string; @IsOptional() @IsString() jobTitle?:string; @IsOptional() @IsUUID() ownerUserUuid?:string; @IsOptional() @IsString() source?:string; }
export class ContactPatchDto { @IsOptional() @IsString() firstName?:string; @IsOptional() @IsString() lastName?:string; @IsOptional() @IsString() displayName?:string; @IsOptional() @IsString() companyName?:string; @IsOptional() @IsString() jobTitle?:string; }
export class AddressDto { @IsString() type!:string; @IsString() line1!:string; @IsOptional() @IsString() line2?:string; @IsString() city!:string; @IsOptional() @IsString() region?:string; @IsOptional() @IsString() postalCode?:string; @IsString() countryCode!:string; @IsOptional() @IsBoolean() isPrimary?:boolean; }
export class PhoneDto { @IsString() type!:string; @IsString() value!:string; @IsOptional() @IsBoolean() isPrimary?:boolean; }
export class EmailDto { @IsString() type!:string; @IsEmail() value!:string; @IsOptional() @IsBoolean() isPrimary?:boolean; }
export class PreferenceDto { @IsOptional() @IsString() preferredChannel?:string; @IsOptional() @IsString() preferredLanguage?:string; @IsOptional() @IsBoolean() marketingEmail?:boolean; @IsOptional() @IsBoolean() marketingSms?:boolean; @IsOptional() @IsBoolean() marketingWhatsapp?:boolean; @IsOptional() @IsString() quietHoursStart?:string; @IsOptional() @IsString() quietHoursEnd?:string; @IsOptional() @IsString() timezone?:string; }
export class ConsentDto { @IsString() consentType!:string; @IsIn(['GRANTED','REVOKED']) status!:string; @IsString() source!:string; }
export class RelationshipDto { @IsUUID() targetContactUuid!:string; @IsString() relationshipType!:string; @IsOptional() @IsBoolean() isReciprocal?:boolean; }
export class LeadDto { @IsUUID() contactUuid!:string; @IsUUID() sourceUuid!:string; @IsUUID() typeUuid!:string; @IsOptional() @IsUUID() campaignUuid?:string; @IsOptional() @IsUUID() statusUuid?:string; @IsOptional() @IsString() code?:string; }
export class LeadPatchDto { @IsOptional() @IsString() code?:string; @IsOptional() @IsUUID() campaignUuid?:string; }
export class ConfigDto { @IsString() code!:string; @IsString() name!:string; @IsOptional() @IsString() description?:string; @IsOptional() @IsInt() sortOrder?:number; @IsOptional() @IsBoolean() isClosed?:boolean; @IsOptional() @IsString() color?:string; @IsOptional() @IsUUID() sourceUuid?:string; @IsOptional() @IsISO8601() startsAt?:string; @IsOptional() @IsISO8601() endsAt?:string; }
export class NoteDto { @IsString() @MinLength(1) body!:string; }
export class AssignmentDto { @IsUUID() userUuid!:string; }
export class StatusDto { @IsUUID() statusUuid!:string; }
export class ScoreRuleDto { @IsString() code!:string; @IsString() field!:string; @IsString() operator!:string; @IsString() value!:string; @IsInt() points!:number; @IsOptional() @IsInt() priority?:number; @IsOptional() @IsBoolean() isActive?:boolean; }
export class DuplicateReviewDto { @IsIn(['CONFIRMED','IGNORED']) status!:string; }
export class MergeDto { @IsUUID() targetLeadUuid!:string; }
export class InquiryDto { @IsIn(['PROPERTY_INQUIRY','CONTACT_MESSAGE','PRICE_REQUEST','CALLBACK_REQUEST','CONSULTATION','BROCHURE_REQUEST','VIEWING_REQUEST']) intent!:string; @IsOptional() @IsUUID() contactUuid?:string; @IsOptional() @IsUUID() propertyUuid?:string; @IsOptional() @IsString() requesterName?:string; @IsOptional() @IsEmail() requesterEmail?:string; @IsOptional() @IsString() requesterPhone?:string; @IsOptional() @IsString() message?:string; @IsOptional() @IsString() preferredChannel?:string; @IsOptional() @IsISO8601() preferredAt?:string; @IsOptional() @IsString() timezone?:string; @IsOptional() @IsString() deliveryPreference?:string; @IsOptional() @IsString() serviceContext?:string; @IsOptional() @IsString() website?:string; @IsOptional() @IsString() captchaToken?:string; }
export class InquiryPatchDto { @IsOptional() @IsString() status?:string; @IsOptional() @IsUUID() contactUuid?:string; @IsOptional() @IsString() message?:string; }
export class ConversionDto { @IsUUID() sourceUuid!:string; @IsUUID() typeUuid!:string; @IsUUID() statusUuid!:string; @IsOptional() @IsString() code?:string; }
export class ActivityDto { @IsIn(['TASK','FOLLOW_UP','CALL','MEETING','REMINDER','NOTE']) type!:string; @IsString() subject!:string; @IsOptional() @IsString() description?:string; @IsOptional() @IsUUID() contactUuid?:string; @IsOptional() @IsUUID() leadUuid?:string; @IsOptional() @IsUUID() assigneeUserUuid?:string; @IsOptional() @IsString() priority?:string; @IsOptional() @IsISO8601() dueAt?:string; @IsOptional() @IsString() callOutcome?:string; @IsOptional() @IsInt() durationSeconds?:number; @IsOptional() @IsISO8601() meetingStartAt?:string; @IsOptional() @IsISO8601() meetingEndAt?:string; @IsOptional() @IsString() location?:string; @IsOptional() @IsISO8601() reminderAt?:string; }
export class ActivityPatchDto { @IsOptional() @IsString() subject?:string; @IsOptional() @IsString() description?:string; @IsOptional() @IsISO8601() dueAt?:string; @IsOptional() @IsUUID() assigneeUserUuid?:string; }
export class ActivityStatusDto { @IsIn(['CREATED','ASSIGNED','IN_PROGRESS','COMPLETED','CANCELLED']) status!:string; }
export class CommunicationDto { @IsIn(['EMAIL','WHATSAPP','SMS']) channel!:string; @IsOptional() @IsIn(['INBOUND','OUTBOUND']) direction?:string; @IsOptional() @IsUUID() contactUuid?:string; @IsOptional() @IsUUID() leadUuid?:string; @IsOptional() @IsUUID() activityUuid?:string; @IsOptional() @IsUUID() templateUuid?:string; @IsOptional() @IsString() providerName?:string; @IsString() destination!:string; @IsOptional() @IsString() subject?:string; @IsString() body!:string; }
export class CommunicationStatusDto { @IsIn(['SENT','DELIVERED','FAILED','CANCELLED']) status!:string; @IsOptional() @IsString() providerMessageId?:string; @IsOptional() @IsString() providerError?:string; }
export class TemplateDto { @IsString() code!:string; @IsString() name!:string; @IsIn(['EMAIL','WHATSAPP','SMS']) channel!:string; @IsOptional() @IsString() subject?:string; @IsString() body!:string; }
