CREATE TABLE `system_import_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `actor_uuid` CHAR(36) NOT NULL,
  `filename` VARCHAR(255) NOT NULL,
  `format` VARCHAR(8) NOT NULL,
  `state` VARCHAR(16) NOT NULL,
  `preview` BOOLEAN NOT NULL DEFAULT FALSE,
  `idempotency_key` VARCHAR(128) NULL,
  `total_rows` INT NOT NULL DEFAULT 0,
  `processed_rows` INT NOT NULL DEFAULT 0,
  `failed_rows` INT NOT NULL DEFAULT 0,
  `errors` JSON NOT NULL,
  `source_path` VARCHAR(500) NULL,
  `expires_at` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `system_import_jobs_uuid_key` (`uuid`),
  UNIQUE KEY `system_import_jobs_actor_idempotency_key_key` (`actor_uuid`,`idempotency_key`),
  KEY `system_import_jobs_actor_created_idx` (`actor_uuid`,`created_at`),
  KEY `system_import_jobs_state_expires_idx` (`state`,`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `system_export_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `actor_uuid` CHAR(36) NOT NULL,
  `entity` VARCHAR(40) NOT NULL,
  `format` VARCHAR(8) NOT NULL,
  `state` VARCHAR(16) NOT NULL,
  `filters` JSON NOT NULL,
  `artifact_path` VARCHAR(500) NULL,
  `download_token_hash` CHAR(64) NULL,
  `rows` INT NOT NULL DEFAULT 0,
  `expires_at` DATETIME(3) NOT NULL,
  `error_message` VARCHAR(500) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `system_export_jobs_uuid_key` (`uuid`),
  KEY `system_export_jobs_actor_created_idx` (`actor_uuid`,`created_at`),
  KEY `system_export_jobs_state_expires_idx` (`state`,`expires_at`),
  KEY `system_export_jobs_download_token_idx` (`download_token_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
