export const SYSTEM_ERROR_CODES = {
  SETTING_NOT_FOUND: 'SYSTEM_SETTING_NOT_FOUND',
  SETTING_IMMUTABLE: 'SYSTEM_SETTING_IMMUTABLE',
  SETTING_CONFLICT: 'SYSTEM_SETTING_CONFLICT',
  SETTING_INVALID: 'SYSTEM_SETTING_INVALID',
  ACTIVITY_INVALID: 'SYSTEM_ACTIVITY_INVALID',
  JOB_NOT_FOUND: 'SYSTEM_JOB_NOT_FOUND',
  JOB_INVALID_STATE: 'SYSTEM_JOB_INVALID_STATE',
  NOTIFICATION_NOT_FOUND: 'SYSTEM_NOTIFICATION_NOT_FOUND',
} as const;

export type SystemErrorCode =
  (typeof SYSTEM_ERROR_CODES)[keyof typeof SYSTEM_ERROR_CODES];
