export const MATCHING_AUDIT_ACTIONS = {
  PREFERENCE_CREATED: 'PROPERTY_MATCHING_PREFERENCE_CREATED',
  PREFERENCE_UPDATED: 'PROPERTY_MATCHING_PREFERENCE_UPDATED',
  PREFERENCE_ARCHIVED: 'PROPERTY_MATCHING_PREFERENCE_ARCHIVED',
  RECOMMENDATION_GENERATED: 'PROPERTY_MATCHING_RECOMMENDATION_GENERATED',
  RECOMMENDATION_REFRESHED: 'PROPERTY_MATCHING_RECOMMENDATION_REFRESHED',
  FEEDBACK_RECORDED: 'PROPERTY_MATCHING_FEEDBACK_RECORDED',
} as const;